project: proof-rust

estates:
  proof-rust:
    hostname: proof-rust.getecosphere.com
    ingress: tunnel
    cloudflare_account: getecosphere
    services:
      - proof-rust
      - auth-backend
      - auth-ui
      - profile-backend
      - profile-ui

services:
  proof-rust:
    path: .
    runtimes:
      - rust

  auth-backend:
    lxs: auth@1.1.0

  auth-ui:
    lxs: auth-ui@0.1.0

  profile-backend:
    lxs: profile@1.1.0

  profile-ui:
    lxs: profile-ui@0.1.0

auth:
  email_verification:
    enabled: false
